[settings]
  # Stop on page processing errors?
  strict = true

  # Display progress?
  verbose = true

  # Display detailed debug output?
  debug = false

  # Where input files (pages and assets) are stored.
  site_dir = "src"

  # Where the output goes
  build_dir = "_site"

  # Pages will other extensions are considered static assets
  # and copied to build/ unchanged
  page_file_extensions = ["html", "md"]

  # Files with these extensions are ignored.
  ignore_extensions = ["draft"]

  # Treat files as content to insert in the template,
  # unless they have an <html> element in them.
  generator_mode = true
  complete_page_selector = "html"

  # Use templates/main.html file for the page template.
  default_template_file = "templates/main.html"

  # The content will be inserted into its <main> element,
  # after its last already existing child.
  default_content_selector = "main"
  default_content_action = "append_child"

  # Set the document type to HTML5, unless the page already has
  # a doctype declaration.
  doctype = "<!DOCTYPE html>"
  keep_doctype = true

  # Indent HTML tags for readability
  pretty_print_html = true

  # Translate site/about.html to build/about/index.html
  # If set to false, then site/about.html will become build/about.html
  clean_urls = false

  # Look for plugin files in plugins/
  plugin_discovery = true
  plugin_dirs = ["plugins"]


[preprocessors]
  md = 'pandoc -f markdown -t html'


[widgets.page-title]
  widget = "title"
  selector = "h1"
  default = "dbp.io"
  append = ""
  prepend = "dbp.io :: "

  # Insert a <title> element if a page doesn't have one
  force = false

  # Keep the existing <title> if it exists and isn't empty
  keep = false
